In [1]:
import numpy as np
import time


In [2]:
# 1D Array
arr1 = np.array([10, 20, 30, 40, 50])

# 2D Array
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(arr1)
print(arr2)


[10 20 30 40 50]
[[1 2 3]
 [4 5 6]]


In [3]:
print(arr1[0])        # First element
print(arr1[1:4])      # Slicing

print(arr2[0, 1])     # Row 0, Column 1


10
[20 30 40]
2


In [4]:
print(arr1 + 5)
print(arr1 * 2)

print(np.sum(arr1))
print(np.max(arr1))
print(np.min(arr1))


[15 25 35 45 55]
[ 20  40  60  80 100]
150
50
10


In [5]:
print("Mean:", np.mean(arr1))
print("Median:", np.median(arr1))
print("Standard Deviation:", np.std(arr1))


Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951


In [6]:
print("Column Sum:", np.sum(arr2, axis=0))
print("Row Sum:", np.sum(arr2, axis=1))


Column Sum: [5 7 9]
Row Sum: [ 6 15]


In [7]:
arr3 = np.arange(1, 13)
reshaped = arr3.reshape(3, 4)

print(reshaped)

# Broadcasting
print(reshaped + 10)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


In [8]:
np.save("data.npy", reshaped)

loaded_data = np.load("data.npy")
print(loaded_data)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
size = 1000000

python_list = list(range(size))
numpy_array = np.arange(size)

# Python List
start = time.time()
python_list = [x * 2 for x in python_list]
print("Python List Time:", time.time() - start)

# NumPy Array
start = time.time()
numpy_array = numpy_array * 2
print("NumPy Array Time:", time.time() - start)


Python List Time: 0.17746520042419434
NumPy Array Time: 0.004425048828125


In [10]:
print("Project Completed Successfully!")


Project Completed Successfully!
